// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package handlers

//go:generate minimock -i github.com/alonsoF100/chat-api/internal/transport/http/handlers.Service -o service_mock_test.go -n ServiceMock -p handlers

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/alonsoF100/chat-api/internal/models"
	"github.com/gojuno/minimock/v3"
)

// ServiceMock implements Service
type ServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreateChat          func(title string) (cp1 *models.Chat, err error)
	funcCreateChatOrigin    string
	inspectFuncCreateChat   func(title string)
	afterCreateChatCounter  uint64
	beforeCreateChatCounter uint64
	CreateChatMock          mServiceMockCreateChat

	funcCreateMessage          func(text string, chatID int) (mp1 *models.Message, err error)
	funcCreateMessageOrigin    string
	inspectFuncCreateMessage   func(text string, chatID int)
	afterCreateMessageCounter  uint64
	beforeCreateMessageCounter uint64
	CreateMessageMock          mServiceMockCreateMessage

	funcDeleteChat          func(chatID int) (err error)
	funcDeleteChatOrigin    string
	inspectFuncDeleteChat   func(chatID int)
	afterDeleteChatCounter  uint64
	beforeDeleteChatCounter uint64
	DeleteChatMock          mServiceMockDeleteChat

	funcGetMessages          func(chatID int, limit int) (cp1 *models.ChatWithMessages, err error)
	funcGetMessagesOrigin    string
	inspectFuncGetMessages   func(chatID int, limit int)
	afterGetMessagesCounter  uint64
	beforeGetMessagesCounter uint64
	GetMessagesMock          mServiceMockGetMessages
}

// NewServiceMock returns a mock for Service
func NewServiceMock(t minimock.Tester) *ServiceMock {
	m := &ServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateChatMock = mServiceMockCreateChat{mock: m}
	m.CreateChatMock.callArgs = []*ServiceMockCreateChatParams{}

	m.CreateMessageMock = mServiceMockCreateMessage{mock: m}
	m.CreateMessageMock.callArgs = []*ServiceMockCreateMessageParams{}

	m.DeleteChatMock = mServiceMockDeleteChat{mock: m}
	m.DeleteChatMock.callArgs = []*ServiceMockDeleteChatParams{}

	m.GetMessagesMock = mServiceMockGetMessages{mock: m}
	m.GetMessagesMock.callArgs = []*ServiceMockGetMessagesParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mServiceMockCreateChat struct {
	optional           bool
	mock               *ServiceMock
	defaultExpectation *ServiceMockCreateChatExpectation
	expectations       []*ServiceMockCreateChatExpectation

	callArgs []*ServiceMockCreateChatParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ServiceMockCreateChatExpectation specifies expectation struct of the Service.CreateChat
type ServiceMockCreateChatExpectation struct {
	mock               *ServiceMock
	params             *ServiceMockCreateChatParams
	paramPtrs          *ServiceMockCreateChatParamPtrs
	expectationOrigins ServiceMockCreateChatExpectationOrigins
	results            *ServiceMockCreateChatResults
	returnOrigin       string
	Counter            uint64
}

// ServiceMockCreateChatParams contains parameters of the Service.CreateChat
type ServiceMockCreateChatParams struct {
	title string
}

// ServiceMockCreateChatParamPtrs contains pointers to parameters of the Service.CreateChat
type ServiceMockCreateChatParamPtrs struct {
	title *string
}

// ServiceMockCreateChatResults contains results of the Service.CreateChat
type ServiceMockCreateChatResults struct {
	cp1 *models.Chat
	err error
}

// ServiceMockCreateChatOrigins contains origins of expectations of the Service.CreateChat
type ServiceMockCreateChatExpectationOrigins struct {
	origin      string
	originTitle string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateChat *mServiceMockCreateChat) Optional() *mServiceMockCreateChat {
	mmCreateChat.optional = true
	return mmCreateChat
}

// Expect sets up expected params for Service.CreateChat
func (mmCreateChat *mServiceMockCreateChat) Expect(title string) *mServiceMockCreateChat {
	if mmCreateChat.mock.funcCreateChat != nil {
		mmCreateChat.mock.t.Fatalf("ServiceMock.CreateChat mock is already set by Set")
	}

	if mmCreateChat.defaultExpectation == nil {
		mmCreateChat.defaultExpectation = &ServiceMockCreateChatExpectation{}
	}

	if mmCreateChat.defaultExpectation.paramPtrs != nil {
		mmCreateChat.mock.t.Fatalf("ServiceMock.CreateChat mock is already set by ExpectParams functions")
	}

	mmCreateChat.defaultExpectation.params = &ServiceMockCreateChatParams{title}
	mmCreateChat.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateChat.expectations {
		if minimock.Equal(e.params, mmCreateChat.defaultExpectation.params) {
			mmCreateChat.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateChat.defaultExpectation.params)
		}
	}

	return mmCreateChat
}

// ExpectTitleParam1 sets up expected param title for Service.CreateChat
func (mmCreateChat *mServiceMockCreateChat) ExpectTitleParam1(title string) *mServiceMockCreateChat {
	if mmCreateChat.mock.funcCreateChat != nil {
		mmCreateChat.mock.t.Fatalf("ServiceMock.CreateChat mock is already set by Set")
	}

	if mmCreateChat.defaultExpectation == nil {
		mmCreateChat.defaultExpectation = &ServiceMockCreateChatExpectation{}
	}

	if mmCreateChat.defaultExpectation.params != nil {
		mmCreateChat.mock.t.Fatalf("ServiceMock.CreateChat mock is already set by Expect")
	}

	if mmCreateChat.defaultExpectation.paramPtrs == nil {
		mmCreateChat.defaultExpectation.paramPtrs = &ServiceMockCreateChatParamPtrs{}
	}
	mmCreateChat.defaultExpectation.paramPtrs.title = &title
	mmCreateChat.defaultExpectation.expectationOrigins.originTitle = minimock.CallerInfo(1)

	return mmCreateChat
}

// Inspect accepts an inspector function that has same arguments as the Service.CreateChat
func (mmCreateChat *mServiceMockCreateChat) Inspect(f func(title string)) *mServiceMockCreateChat {
	if mmCreateChat.mock.inspectFuncCreateChat != nil {
		mmCreateChat.mock.t.Fatalf("Inspect function is already set for ServiceMock.CreateChat")
	}

	mmCreateChat.mock.inspectFuncCreateChat = f

	return mmCreateChat
}

// Return sets up results that will be returned by Service.CreateChat
func (mmCreateChat *mServiceMockCreateChat) Return(cp1 *models.Chat, err error) *ServiceMock {
	if mmCreateChat.mock.funcCreateChat != nil {
		mmCreateChat.mock.t.Fatalf("ServiceMock.CreateChat mock is already set by Set")
	}

	if mmCreateChat.defaultExpectation == nil {
		mmCreateChat.defaultExpectation = &ServiceMockCreateChatExpectation{mock: mmCreateChat.mock}
	}
	mmCreateChat.defaultExpectation.results = &ServiceMockCreateChatResults{cp1, err}
	mmCreateChat.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateChat.mock
}

// Set uses given function f to mock the Service.CreateChat method
func (mmCreateChat *mServiceMockCreateChat) Set(f func(title string) (cp1 *models.Chat, err error)) *ServiceMock {
	if mmCreateChat.defaultExpectation != nil {
		mmCreateChat.mock.t.Fatalf("Default expectation is already set for the Service.CreateChat method")
	}

	if len(mmCreateChat.expectations) > 0 {
		mmCreateChat.mock.t.Fatalf("Some expectations are already set for the Service.CreateChat method")
	}

	mmCreateChat.mock.funcCreateChat = f
	mmCreateChat.mock.funcCreateChatOrigin = minimock.CallerInfo(1)
	return mmCreateChat.mock
}

// When sets expectation for the Service.CreateChat which will trigger the result defined by the following
// Then helper
func (mmCreateChat *mServiceMockCreateChat) When(title string) *ServiceMockCreateChatExpectation {
	if mmCreateChat.mock.funcCreateChat != nil {
		mmCreateChat.mock.t.Fatalf("ServiceMock.CreateChat mock is already set by Set")
	}

	expectation := &ServiceMockCreateChatExpectation{
		mock:               mmCreateChat.mock,
		params:             &ServiceMockCreateChatParams{title},
		expectationOrigins: ServiceMockCreateChatExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateChat.expectations = append(mmCreateChat.expectations, expectation)
	return expectation
}

// Then sets up Service.CreateChat return parameters for the expectation previously defined by the When method
func (e *ServiceMockCreateChatExpectation) Then(cp1 *models.Chat, err error) *ServiceMock {
	e.results = &ServiceMockCreateChatResults{cp1, err}
	return e.mock
}

// Times sets number of times Service.CreateChat should be invoked
func (mmCreateChat *mServiceMockCreateChat) Times(n uint64) *mServiceMockCreateChat {
	if n == 0 {
		mmCreateChat.mock.t.Fatalf("Times of ServiceMock.CreateChat mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateChat.expectedInvocations, n)
	mmCreateChat.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateChat
}

func (mmCreateChat *mServiceMockCreateChat) invocationsDone() bool {
	if len(mmCreateChat.expectations) == 0 && mmCreateChat.defaultExpectation == nil && mmCreateChat.mock.funcCreateChat == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateChat.mock.afterCreateChatCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateChat.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateChat implements Service
func (mmCreateChat *ServiceMock) CreateChat(title string) (cp1 *models.Chat, err error) {
	mm_atomic.AddUint64(&mmCreateChat.beforeCreateChatCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateChat.afterCreateChatCounter, 1)

	mmCreateChat.t.Helper()

	if mmCreateChat.inspectFuncCreateChat != nil {
		mmCreateChat.inspectFuncCreateChat(title)
	}

	mm_params := ServiceMockCreateChatParams{title}

	// Record call args
	mmCreateChat.CreateChatMock.mutex.Lock()
	mmCreateChat.CreateChatMock.callArgs = append(mmCreateChat.CreateChatMock.callArgs, &mm_params)
	mmCreateChat.CreateChatMock.mutex.Unlock()

	for _, e := range mmCreateChat.CreateChatMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.cp1, e.results.err
		}
	}

	if mmCreateChat.CreateChatMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateChat.CreateChatMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateChat.CreateChatMock.defaultExpectation.params
		mm_want_ptrs := mmCreateChat.CreateChatMock.defaultExpectation.paramPtrs

		mm_got := ServiceMockCreateChatParams{title}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.title != nil && !minimock.Equal(*mm_want_ptrs.title, mm_got.title) {
				mmCreateChat.t.Errorf("ServiceMock.CreateChat got unexpected parameter title, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateChat.CreateChatMock.defaultExpectation.expectationOrigins.originTitle, *mm_want_ptrs.title, mm_got.title, minimock.Diff(*mm_want_ptrs.title, mm_got.title))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateChat.t.Errorf("ServiceMock.CreateChat got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateChat.CreateChatMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateChat.CreateChatMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateChat.t.Fatal("No results are set for the ServiceMock.CreateChat")
		}
		return (*mm_results).cp1, (*mm_results).err
	}
	if mmCreateChat.funcCreateChat != nil {
		return mmCreateChat.funcCreateChat(title)
	}
	mmCreateChat.t.Fatalf("Unexpected call to ServiceMock.CreateChat. %v", title)
	return
}

// CreateChatAfterCounter returns a count of finished ServiceMock.CreateChat invocations
func (mmCreateChat *ServiceMock) CreateChatAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateChat.afterCreateChatCounter)
}

// CreateChatBeforeCounter returns a count of ServiceMock.CreateChat invocations
func (mmCreateChat *ServiceMock) CreateChatBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateChat.beforeCreateChatCounter)
}

// Calls returns a list of arguments used in each call to ServiceMock.CreateChat.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateChat *mServiceMockCreateChat) Calls() []*ServiceMockCreateChatParams {
	mmCreateChat.mutex.RLock()

	argCopy := make([]*ServiceMockCreateChatParams, len(mmCreateChat.callArgs))
	copy(argCopy, mmCreateChat.callArgs)

	mmCreateChat.mutex.RUnlock()

	return argCopy
}

// MinimockCreateChatDone returns true if the count of the CreateChat invocations corresponds
// the number of defined expectations
func (m *ServiceMock) MinimockCreateChatDone() bool {
	if m.CreateChatMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateChatMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateChatMock.invocationsDone()
}

// MinimockCreateChatInspect logs each unmet expectation
func (m *ServiceMock) MinimockCreateChatInspect() {
	for _, e := range m.CreateChatMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ServiceMock.CreateChat at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateChatCounter := mm_atomic.LoadUint64(&m.afterCreateChatCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateChatMock.defaultExpectation != nil && afterCreateChatCounter < 1 {
		if m.CreateChatMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ServiceMock.CreateChat at\n%s", m.CreateChatMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ServiceMock.CreateChat at\n%s with params: %#v", m.CreateChatMock.defaultExpectation.expectationOrigins.origin, *m.CreateChatMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateChat != nil && afterCreateChatCounter < 1 {
		m.t.Errorf("Expected call to ServiceMock.CreateChat at\n%s", m.funcCreateChatOrigin)
	}

	if !m.CreateChatMock.invocationsDone() && afterCreateChatCounter > 0 {
		m.t.Errorf("Expected %d calls to ServiceMock.CreateChat at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateChatMock.expectedInvocations), m.CreateChatMock.expectedInvocationsOrigin, afterCreateChatCounter)
	}
}

type mServiceMockCreateMessage struct {
	optional           bool
	mock               *ServiceMock
	defaultExpectation *ServiceMockCreateMessageExpectation
	expectations       []*ServiceMockCreateMessageExpectation

	callArgs []*ServiceMockCreateMessageParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ServiceMockCreateMessageExpectation specifies expectation struct of the Service.CreateMessage
type ServiceMockCreateMessageExpectation struct {
	mock               *ServiceMock
	params             *ServiceMockCreateMessageParams
	paramPtrs          *ServiceMockCreateMessageParamPtrs
	expectationOrigins ServiceMockCreateMessageExpectationOrigins
	results            *ServiceMockCreateMessageResults
	returnOrigin       string
	Counter            uint64
}

// ServiceMockCreateMessageParams contains parameters of the Service.CreateMessage
type ServiceMockCreateMessageParams struct {
	text   string
	chatID int
}

// ServiceMockCreateMessageParamPtrs contains pointers to parameters of the Service.CreateMessage
type ServiceMockCreateMessageParamPtrs struct {
	text   *string
	chatID *int
}

// ServiceMockCreateMessageResults contains results of the Service.CreateMessage
type ServiceMockCreateMessageResults struct {
	mp1 *models.Message
	err error
}

// ServiceMockCreateMessageOrigins contains origins of expectations of the Service.CreateMessage
type ServiceMockCreateMessageExpectationOrigins struct {
	origin       string
	originText   string
	originChatID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateMessage *mServiceMockCreateMessage) Optional() *mServiceMockCreateMessage {
	mmCreateMessage.optional = true
	return mmCreateMessage
}

// Expect sets up expected params for Service.CreateMessage
func (mmCreateMessage *mServiceMockCreateMessage) Expect(text string, chatID int) *mServiceMockCreateMessage {
	if mmCreateMessage.mock.funcCreateMessage != nil {
		mmCreateMessage.mock.t.Fatalf("ServiceMock.CreateMessage mock is already set by Set")
	}

	if mmCreateMessage.defaultExpectation == nil {
		mmCreateMessage.defaultExpectation = &ServiceMockCreateMessageExpectation{}
	}

	if mmCreateMessage.defaultExpectation.paramPtrs != nil {
		mmCreateMessage.mock.t.Fatalf("ServiceMock.CreateMessage mock is already set by ExpectParams functions")
	}

	mmCreateMessage.defaultExpectation.params = &ServiceMockCreateMessageParams{text, chatID}
	mmCreateMessage.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateMessage.expectations {
		if minimock.Equal(e.params, mmCreateMessage.defaultExpectation.params) {
			mmCreateMessage.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateMessage.defaultExpectation.params)
		}
	}

	return mmCreateMessage
}

// ExpectTextParam1 sets up expected param text for Service.CreateMessage
func (mmCreateMessage *mServiceMockCreateMessage) ExpectTextParam1(text string) *mServiceMockCreateMessage {
	if mmCreateMessage.mock.funcCreateMessage != nil {
		mmCreateMessage.mock.t.Fatalf("ServiceMock.CreateMessage mock is already set by Set")
	}

	if mmCreateMessage.defaultExpectation == nil {
		mmCreateMessage.defaultExpectation = &ServiceMockCreateMessageExpectation{}
	}

	if mmCreateMessage.defaultExpectation.params != nil {
		mmCreateMessage.mock.t.Fatalf("ServiceMock.CreateMessage mock is already set by Expect")
	}

	if mmCreateMessage.defaultExpectation.paramPtrs == nil {
		mmCreateMessage.defaultExpectation.paramPtrs = &ServiceMockCreateMessageParamPtrs{}
	}
	mmCreateMessage.defaultExpectation.paramPtrs.text = &text
	mmCreateMessage.defaultExpectation.expectationOrigins.originText = minimock.CallerInfo(1)

	return mmCreateMessage
}

// ExpectChatIDParam2 sets up expected param chatID for Service.CreateMessage
func (mmCreateMessage *mServiceMockCreateMessage) ExpectChatIDParam2(chatID int) *mServiceMockCreateMessage {
	if mmCreateMessage.mock.funcCreateMessage != nil {
		mmCreateMessage.mock.t.Fatalf("ServiceMock.CreateMessage mock is already set by Set")
	}

	if mmCreateMessage.defaultExpectation == nil {
		mmCreateMessage.defaultExpectation = &ServiceMockCreateMessageExpectation{}
	}

	if mmCreateMessage.defaultExpectation.params != nil {
		mmCreateMessage.mock.t.Fatalf("ServiceMock.CreateMessage mock is already set by Expect")
	}

	if mmCreateMessage.defaultExpectation.paramPtrs == nil {
		mmCreateMessage.defaultExpectation.paramPtrs = &ServiceMockCreateMessageParamPtrs{}
	}
	mmCreateMessage.defaultExpectation.paramPtrs.chatID = &chatID
	mmCreateMessage.defaultExpectation.expectationOrigins.originChatID = minimock.CallerInfo(1)

	return mmCreateMessage
}

// Inspect accepts an inspector function that has same arguments as the Service.CreateMessage
func (mmCreateMessage *mServiceMockCreateMessage) Inspect(f func(text string, chatID int)) *mServiceMockCreateMessage {
	if mmCreateMessage.mock.inspectFuncCreateMessage != nil {
		mmCreateMessage.mock.t.Fatalf("Inspect function is already set for ServiceMock.CreateMessage")
	}

	mmCreateMessage.mock.inspectFuncCreateMessage = f

	return mmCreateMessage
}

// Return sets up results that will be returned by Service.CreateMessage
func (mmCreateMessage *mServiceMockCreateMessage) Return(mp1 *models.Message, err error) *ServiceMock {
	if mmCreateMessage.mock.funcCreateMessage != nil {
		mmCreateMessage.mock.t.Fatalf("ServiceMock.CreateMessage mock is already set by Set")
	}

	if mmCreateMessage.defaultExpectation == nil {
		mmCreateMessage.defaultExpectation = &ServiceMockCreateMessageExpectation{mock: mmCreateMessage.mock}
	}
	mmCreateMessage.defaultExpectation.results = &ServiceMockCreateMessageResults{mp1, err}
	mmCreateMessage.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateMessage.mock
}

// Set uses given function f to mock the Service.CreateMessage method
func (mmCreateMessage *mServiceMockCreateMessage) Set(f func(text string, chatID int) (mp1 *models.Message, err error)) *ServiceMock {
	if mmCreateMessage.defaultExpectation != nil {
		mmCreateMessage.mock.t.Fatalf("Default expectation is already set for the Service.CreateMessage method")
	}

	if len(mmCreateMessage.expectations) > 0 {
		mmCreateMessage.mock.t.Fatalf("Some expectations are already set for the Service.CreateMessage method")
	}

	mmCreateMessage.mock.funcCreateMessage = f
	mmCreateMessage.mock.funcCreateMessageOrigin = minimock.CallerInfo(1)
	return mmCreateMessage.mock
}

// When sets expectation for the Service.CreateMessage which will trigger the result defined by the following
// Then helper
func (mmCreateMessage *mServiceMockCreateMessage) When(text string, chatID int) *ServiceMockCreateMessageExpectation {
	if mmCreateMessage.mock.funcCreateMessage != nil {
		mmCreateMessage.mock.t.Fatalf("ServiceMock.CreateMessage mock is already set by Set")
	}

	expectation := &ServiceMockCreateMessageExpectation{
		mock:               mmCreateMessage.mock,
		params:             &ServiceMockCreateMessageParams{text, chatID},
		expectationOrigins: ServiceMockCreateMessageExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateMessage.expectations = append(mmCreateMessage.expectations, expectation)
	return expectation
}

// Then sets up Service.CreateMessage return parameters for the expectation previously defined by the When method
func (e *ServiceMockCreateMessageExpectation) Then(mp1 *models.Message, err error) *ServiceMock {
	e.results = &ServiceMockCreateMessageResults{mp1, err}
	return e.mock
}

// Times sets number of times Service.CreateMessage should be invoked
func (mmCreateMessage *mServiceMockCreateMessage) Times(n uint64) *mServiceMockCreateMessage {
	if n == 0 {
		mmCreateMessage.mock.t.Fatalf("Times of ServiceMock.CreateMessage mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateMessage.expectedInvocations, n)
	mmCreateMessage.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateMessage
}

func (mmCreateMessage *mServiceMockCreateMessage) invocationsDone() bool {
	if len(mmCreateMessage.expectations) == 0 && mmCreateMessage.defaultExpectation == nil && mmCreateMessage.mock.funcCreateMessage == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateMessage.mock.afterCreateMessageCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateMessage.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateMessage implements Service
func (mmCreateMessage *ServiceMock) CreateMessage(text string, chatID int) (mp1 *models.Message, err error) {
	mm_atomic.AddUint64(&mmCreateMessage.beforeCreateMessageCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateMessage.afterCreateMessageCounter, 1)

	mmCreateMessage.t.Helper()

	if mmCreateMessage.inspectFuncCreateMessage != nil {
		mmCreateMessage.inspectFuncCreateMessage(text, chatID)
	}

	mm_params := ServiceMockCreateMessageParams{text, chatID}

	// Record call args
	mmCreateMessage.CreateMessageMock.mutex.Lock()
	mmCreateMessage.CreateMessageMock.callArgs = append(mmCreateMessage.CreateMessageMock.callArgs, &mm_params)
	mmCreateMessage.CreateMessageMock.mutex.Unlock()

	for _, e := range mmCreateMessage.CreateMessageMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.mp1, e.results.err
		}
	}

	if mmCreateMessage.CreateMessageMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateMessage.CreateMessageMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateMessage.CreateMessageMock.defaultExpectation.params
		mm_want_ptrs := mmCreateMessage.CreateMessageMock.defaultExpectation.paramPtrs

		mm_got := ServiceMockCreateMessageParams{text, chatID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.text != nil && !minimock.Equal(*mm_want_ptrs.text, mm_got.text) {
				mmCreateMessage.t.Errorf("ServiceMock.CreateMessage got unexpected parameter text, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateMessage.CreateMessageMock.defaultExpectation.expectationOrigins.originText, *mm_want_ptrs.text, mm_got.text, minimock.Diff(*mm_want_ptrs.text, mm_got.text))
			}

			if mm_want_ptrs.chatID != nil && !minimock.Equal(*mm_want_ptrs.chatID, mm_got.chatID) {
				mmCreateMessage.t.Errorf("ServiceMock.CreateMessage got unexpected parameter chatID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateMessage.CreateMessageMock.defaultExpectation.expectationOrigins.originChatID, *mm_want_ptrs.chatID, mm_got.chatID, minimock.Diff(*mm_want_ptrs.chatID, mm_got.chatID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateMessage.t.Errorf("ServiceMock.CreateMessage got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateMessage.CreateMessageMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateMessage.CreateMessageMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateMessage.t.Fatal("No results are set for the ServiceMock.CreateMessage")
		}
		return (*mm_results).mp1, (*mm_results).err
	}
	if mmCreateMessage.funcCreateMessage != nil {
		return mmCreateMessage.funcCreateMessage(text, chatID)
	}
	mmCreateMessage.t.Fatalf("Unexpected call to ServiceMock.CreateMessage. %v %v", text, chatID)
	return
}

// CreateMessageAfterCounter returns a count of finished ServiceMock.CreateMessage invocations
func (mmCreateMessage *ServiceMock) CreateMessageAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateMessage.afterCreateMessageCounter)
}

// CreateMessageBeforeCounter returns a count of ServiceMock.CreateMessage invocations
func (mmCreateMessage *ServiceMock) CreateMessageBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateMessage.beforeCreateMessageCounter)
}

// Calls returns a list of arguments used in each call to ServiceMock.CreateMessage.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateMessage *mServiceMockCreateMessage) Calls() []*ServiceMockCreateMessageParams {
	mmCreateMessage.mutex.RLock()

	argCopy := make([]*ServiceMockCreateMessageParams, len(mmCreateMessage.callArgs))
	copy(argCopy, mmCreateMessage.callArgs)

	mmCreateMessage.mutex.RUnlock()

	return argCopy
}

// MinimockCreateMessageDone returns true if the count of the CreateMessage invocations corresponds
// the number of defined expectations
func (m *ServiceMock) MinimockCreateMessageDone() bool {
	if m.CreateMessageMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMessageMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMessageMock.invocationsDone()
}

// MinimockCreateMessageInspect logs each unmet expectation
func (m *ServiceMock) MinimockCreateMessageInspect() {
	for _, e := range m.CreateMessageMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ServiceMock.CreateMessage at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateMessageCounter := mm_atomic.LoadUint64(&m.afterCreateMessageCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMessageMock.defaultExpectation != nil && afterCreateMessageCounter < 1 {
		if m.CreateMessageMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ServiceMock.CreateMessage at\n%s", m.CreateMessageMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ServiceMock.CreateMessage at\n%s with params: %#v", m.CreateMessageMock.defaultExpectation.expectationOrigins.origin, *m.CreateMessageMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateMessage != nil && afterCreateMessageCounter < 1 {
		m.t.Errorf("Expected call to ServiceMock.CreateMessage at\n%s", m.funcCreateMessageOrigin)
	}

	if !m.CreateMessageMock.invocationsDone() && afterCreateMessageCounter > 0 {
		m.t.Errorf("Expected %d calls to ServiceMock.CreateMessage at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMessageMock.expectedInvocations), m.CreateMessageMock.expectedInvocationsOrigin, afterCreateMessageCounter)
	}
}

type mServiceMockDeleteChat struct {
	optional           bool
	mock               *ServiceMock
	defaultExpectation *ServiceMockDeleteChatExpectation
	expectations       []*ServiceMockDeleteChatExpectation

	callArgs []*ServiceMockDeleteChatParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ServiceMockDeleteChatExpectation specifies expectation struct of the Service.DeleteChat
type ServiceMockDeleteChatExpectation struct {
	mock               *ServiceMock
	params             *ServiceMockDeleteChatParams
	paramPtrs          *ServiceMockDeleteChatParamPtrs
	expectationOrigins ServiceMockDeleteChatExpectationOrigins
	results            *ServiceMockDeleteChatResults
	returnOrigin       string
	Counter            uint64
}

// ServiceMockDeleteChatParams contains parameters of the Service.DeleteChat
type ServiceMockDeleteChatParams struct {
	chatID int
}

// ServiceMockDeleteChatParamPtrs contains pointers to parameters of the Service.DeleteChat
type ServiceMockDeleteChatParamPtrs struct {
	chatID *int
}

// ServiceMockDeleteChatResults contains results of the Service.DeleteChat
type ServiceMockDeleteChatResults struct {
	err error
}

// ServiceMockDeleteChatOrigins contains origins of expectations of the Service.DeleteChat
type ServiceMockDeleteChatExpectationOrigins struct {
	origin       string
	originChatID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDeleteChat *mServiceMockDeleteChat) Optional() *mServiceMockDeleteChat {
	mmDeleteChat.optional = true
	return mmDeleteChat
}

// Expect sets up expected params for Service.DeleteChat
func (mmDeleteChat *mServiceMockDeleteChat) Expect(chatID int) *mServiceMockDeleteChat {
	if mmDeleteChat.mock.funcDeleteChat != nil {
		mmDeleteChat.mock.t.Fatalf("ServiceMock.DeleteChat mock is already set by Set")
	}

	if mmDeleteChat.defaultExpectation == nil {
		mmDeleteChat.defaultExpectation = &ServiceMockDeleteChatExpectation{}
	}

	if mmDeleteChat.defaultExpectation.paramPtrs != nil {
		mmDeleteChat.mock.t.Fatalf("ServiceMock.DeleteChat mock is already set by ExpectParams functions")
	}

	mmDeleteChat.defaultExpectation.params = &ServiceMockDeleteChatParams{chatID}
	mmDeleteChat.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDeleteChat.expectations {
		if minimock.Equal(e.params, mmDeleteChat.defaultExpectation.params) {
			mmDeleteChat.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteChat.defaultExpectation.params)
		}
	}

	return mmDeleteChat
}

// ExpectChatIDParam1 sets up expected param chatID for Service.DeleteChat
func (mmDeleteChat *mServiceMockDeleteChat) ExpectChatIDParam1(chatID int) *mServiceMockDeleteChat {
	if mmDeleteChat.mock.funcDeleteChat != nil {
		mmDeleteChat.mock.t.Fatalf("ServiceMock.DeleteChat mock is already set by Set")
	}

	if mmDeleteChat.defaultExpectation == nil {
		mmDeleteChat.defaultExpectation = &ServiceMockDeleteChatExpectation{}
	}

	if mmDeleteChat.defaultExpectation.params != nil {
		mmDeleteChat.mock.t.Fatalf("ServiceMock.DeleteChat mock is already set by Expect")
	}

	if mmDeleteChat.defaultExpectation.paramPtrs == nil {
		mmDeleteChat.defaultExpectation.paramPtrs = &ServiceMockDeleteChatParamPtrs{}
	}
	mmDeleteChat.defaultExpectation.paramPtrs.chatID = &chatID
	mmDeleteChat.defaultExpectation.expectationOrigins.originChatID = minimock.CallerInfo(1)

	return mmDeleteChat
}

// Inspect accepts an inspector function that has same arguments as the Service.DeleteChat
func (mmDeleteChat *mServiceMockDeleteChat) Inspect(f func(chatID int)) *mServiceMockDeleteChat {
	if mmDeleteChat.mock.inspectFuncDeleteChat != nil {
		mmDeleteChat.mock.t.Fatalf("Inspect function is already set for ServiceMock.DeleteChat")
	}

	mmDeleteChat.mock.inspectFuncDeleteChat = f

	return mmDeleteChat
}

// Return sets up results that will be returned by Service.DeleteChat
func (mmDeleteChat *mServiceMockDeleteChat) Return(err error) *ServiceMock {
	if mmDeleteChat.mock.funcDeleteChat != nil {
		mmDeleteChat.mock.t.Fatalf("ServiceMock.DeleteChat mock is already set by Set")
	}

	if mmDeleteChat.defaultExpectation == nil {
		mmDeleteChat.defaultExpectation = &ServiceMockDeleteChatExpectation{mock: mmDeleteChat.mock}
	}
	mmDeleteChat.defaultExpectation.results = &ServiceMockDeleteChatResults{err}
	mmDeleteChat.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDeleteChat.mock
}

// Set uses given function f to mock the Service.DeleteChat method
func (mmDeleteChat *mServiceMockDeleteChat) Set(f func(chatID int) (err error)) *ServiceMock {
	if mmDeleteChat.defaultExpectation != nil {
		mmDeleteChat.mock.t.Fatalf("Default expectation is already set for the Service.DeleteChat method")
	}

	if len(mmDeleteChat.expectations) > 0 {
		mmDeleteChat.mock.t.Fatalf("Some expectations are already set for the Service.DeleteChat method")
	}

	mmDeleteChat.mock.funcDeleteChat = f
	mmDeleteChat.mock.funcDeleteChatOrigin = minimock.CallerInfo(1)
	return mmDeleteChat.mock
}

// When sets expectation for the Service.DeleteChat which will trigger the result defined by the following
// Then helper
func (mmDeleteChat *mServiceMockDeleteChat) When(chatID int) *ServiceMockDeleteChatExpectation {
	if mmDeleteChat.mock.funcDeleteChat != nil {
		mmDeleteChat.mock.t.Fatalf("ServiceMock.DeleteChat mock is already set by Set")
	}

	expectation := &ServiceMockDeleteChatExpectation{
		mock:               mmDeleteChat.mock,
		params:             &ServiceMockDeleteChatParams{chatID},
		expectationOrigins: ServiceMockDeleteChatExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDeleteChat.expectations = append(mmDeleteChat.expectations, expectation)
	return expectation
}

// Then sets up Service.DeleteChat return parameters for the expectation previously defined by the When method
func (e *ServiceMockDeleteChatExpectation) Then(err error) *ServiceMock {
	e.results = &ServiceMockDeleteChatResults{err}
	return e.mock
}

// Times sets number of times Service.DeleteChat should be invoked
func (mmDeleteChat *mServiceMockDeleteChat) Times(n uint64) *mServiceMockDeleteChat {
	if n == 0 {
		mmDeleteChat.mock.t.Fatalf("Times of ServiceMock.DeleteChat mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDeleteChat.expectedInvocations, n)
	mmDeleteChat.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDeleteChat
}

func (mmDeleteChat *mServiceMockDeleteChat) invocationsDone() bool {
	if len(mmDeleteChat.expectations) == 0 && mmDeleteChat.defaultExpectation == nil && mmDeleteChat.mock.funcDeleteChat == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDeleteChat.mock.afterDeleteChatCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDeleteChat.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DeleteChat implements Service
func (mmDeleteChat *ServiceMock) DeleteChat(chatID int) (err error) {
	mm_atomic.AddUint64(&mmDeleteChat.beforeDeleteChatCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteChat.afterDeleteChatCounter, 1)

	mmDeleteChat.t.Helper()

	if mmDeleteChat.inspectFuncDeleteChat != nil {
		mmDeleteChat.inspectFuncDeleteChat(chatID)
	}

	mm_params := ServiceMockDeleteChatParams{chatID}

	// Record call args
	mmDeleteChat.DeleteChatMock.mutex.Lock()
	mmDeleteChat.DeleteChatMock.callArgs = append(mmDeleteChat.DeleteChatMock.callArgs, &mm_params)
	mmDeleteChat.DeleteChatMock.mutex.Unlock()

	for _, e := range mmDeleteChat.DeleteChatMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDeleteChat.DeleteChatMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteChat.DeleteChatMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteChat.DeleteChatMock.defaultExpectation.params
		mm_want_ptrs := mmDeleteChat.DeleteChatMock.defaultExpectation.paramPtrs

		mm_got := ServiceMockDeleteChatParams{chatID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.chatID != nil && !minimock.Equal(*mm_want_ptrs.chatID, mm_got.chatID) {
				mmDeleteChat.t.Errorf("ServiceMock.DeleteChat got unexpected parameter chatID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteChat.DeleteChatMock.defaultExpectation.expectationOrigins.originChatID, *mm_want_ptrs.chatID, mm_got.chatID, minimock.Diff(*mm_want_ptrs.chatID, mm_got.chatID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteChat.t.Errorf("ServiceMock.DeleteChat got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDeleteChat.DeleteChatMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDeleteChat.DeleteChatMock.defaultExpectation.results
		if mm_results == nil {
			mmDeleteChat.t.Fatal("No results are set for the ServiceMock.DeleteChat")
		}
		return (*mm_results).err
	}
	if mmDeleteChat.funcDeleteChat != nil {
		return mmDeleteChat.funcDeleteChat(chatID)
	}
	mmDeleteChat.t.Fatalf("Unexpected call to ServiceMock.DeleteChat. %v", chatID)
	return
}

// DeleteChatAfterCounter returns a count of finished ServiceMock.DeleteChat invocations
func (mmDeleteChat *ServiceMock) DeleteChatAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteChat.afterDeleteChatCounter)
}

// DeleteChatBeforeCounter returns a count of ServiceMock.DeleteChat invocations
func (mmDeleteChat *ServiceMock) DeleteChatBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteChat.beforeDeleteChatCounter)
}

// Calls returns a list of arguments used in each call to ServiceMock.DeleteChat.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteChat *mServiceMockDeleteChat) Calls() []*ServiceMockDeleteChatParams {
	mmDeleteChat.mutex.RLock()

	argCopy := make([]*ServiceMockDeleteChatParams, len(mmDeleteChat.callArgs))
	copy(argCopy, mmDeleteChat.callArgs)

	mmDeleteChat.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteChatDone returns true if the count of the DeleteChat invocations corresponds
// the number of defined expectations
func (m *ServiceMock) MinimockDeleteChatDone() bool {
	if m.DeleteChatMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteChatMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteChatMock.invocationsDone()
}

// MinimockDeleteChatInspect logs each unmet expectation
func (m *ServiceMock) MinimockDeleteChatInspect() {
	for _, e := range m.DeleteChatMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ServiceMock.DeleteChat at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteChatCounter := mm_atomic.LoadUint64(&m.afterDeleteChatCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteChatMock.defaultExpectation != nil && afterDeleteChatCounter < 1 {
		if m.DeleteChatMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ServiceMock.DeleteChat at\n%s", m.DeleteChatMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ServiceMock.DeleteChat at\n%s with params: %#v", m.DeleteChatMock.defaultExpectation.expectationOrigins.origin, *m.DeleteChatMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteChat != nil && afterDeleteChatCounter < 1 {
		m.t.Errorf("Expected call to ServiceMock.DeleteChat at\n%s", m.funcDeleteChatOrigin)
	}

	if !m.DeleteChatMock.invocationsDone() && afterDeleteChatCounter > 0 {
		m.t.Errorf("Expected %d calls to ServiceMock.DeleteChat at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteChatMock.expectedInvocations), m.DeleteChatMock.expectedInvocationsOrigin, afterDeleteChatCounter)
	}
}

type mServiceMockGetMessages struct {
	optional           bool
	mock               *ServiceMock
	defaultExpectation *ServiceMockGetMessagesExpectation
	expectations       []*ServiceMockGetMessagesExpectation

	callArgs []*ServiceMockGetMessagesParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ServiceMockGetMessagesExpectation specifies expectation struct of the Service.GetMessages
type ServiceMockGetMessagesExpectation struct {
	mock               *ServiceMock
	params             *ServiceMockGetMessagesParams
	paramPtrs          *ServiceMockGetMessagesParamPtrs
	expectationOrigins ServiceMockGetMessagesExpectationOrigins
	results            *ServiceMockGetMessagesResults
	returnOrigin       string
	Counter            uint64
}

// ServiceMockGetMessagesParams contains parameters of the Service.GetMessages
type ServiceMockGetMessagesParams struct {
	chatID int
	limit  int
}

// ServiceMockGetMessagesParamPtrs contains pointers to parameters of the Service.GetMessages
type ServiceMockGetMessagesParamPtrs struct {
	chatID *int
	limit  *int
}

// ServiceMockGetMessagesResults contains results of the Service.GetMessages
type ServiceMockGetMessagesResults struct {
	cp1 *models.ChatWithMessages
	err error
}

// ServiceMockGetMessagesOrigins contains origins of expectations of the Service.GetMessages
type ServiceMockGetMessagesExpectationOrigins struct {
	origin       string
	originChatID string
	originLimit  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetMessages *mServiceMockGetMessages) Optional() *mServiceMockGetMessages {
	mmGetMessages.optional = true
	return mmGetMessages
}

// Expect sets up expected params for Service.GetMessages
func (mmGetMessages *mServiceMockGetMessages) Expect(chatID int, limit int) *mServiceMockGetMessages {
	if mmGetMessages.mock.funcGetMessages != nil {
		mmGetMessages.mock.t.Fatalf("ServiceMock.GetMessages mock is already set by Set")
	}

	if mmGetMessages.defaultExpectation == nil {
		mmGetMessages.defaultExpectation = &ServiceMockGetMessagesExpectation{}
	}

	if mmGetMessages.defaultExpectation.paramPtrs != nil {
		mmGetMessages.mock.t.Fatalf("ServiceMock.GetMessages mock is already set by ExpectParams functions")
	}

	mmGetMessages.defaultExpectation.params = &ServiceMockGetMessagesParams{chatID, limit}
	mmGetMessages.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetMessages.expectations {
		if minimock.Equal(e.params, mmGetMessages.defaultExpectation.params) {
			mmGetMessages.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetMessages.defaultExpectation.params)
		}
	}

	return mmGetMessages
}

// ExpectChatIDParam1 sets up expected param chatID for Service.GetMessages
func (mmGetMessages *mServiceMockGetMessages) ExpectChatIDParam1(chatID int) *mServiceMockGetMessages {
	if mmGetMessages.mock.funcGetMessages != nil {
		mmGetMessages.mock.t.Fatalf("ServiceMock.GetMessages mock is already set by Set")
	}

	if mmGetMessages.defaultExpectation == nil {
		mmGetMessages.defaultExpectation = &ServiceMockGetMessagesExpectation{}
	}

	if mmGetMessages.defaultExpectation.params != nil {
		mmGetMessages.mock.t.Fatalf("ServiceMock.GetMessages mock is already set by Expect")
	}

	if mmGetMessages.defaultExpectation.paramPtrs == nil {
		mmGetMessages.defaultExpectation.paramPtrs = &ServiceMockGetMessagesParamPtrs{}
	}
	mmGetMessages.defaultExpectation.paramPtrs.chatID = &chatID
	mmGetMessages.defaultExpectation.expectationOrigins.originChatID = minimock.CallerInfo(1)

	return mmGetMessages
}

// ExpectLimitParam2 sets up expected param limit for Service.GetMessages
func (mmGetMessages *mServiceMockGetMessages) ExpectLimitParam2(limit int) *mServiceMockGetMessages {
	if mmGetMessages.mock.funcGetMessages != nil {
		mmGetMessages.mock.t.Fatalf("ServiceMock.GetMessages mock is already set by Set")
	}

	if mmGetMessages.defaultExpectation == nil {
		mmGetMessages.defaultExpectation = &ServiceMockGetMessagesExpectation{}
	}

	if mmGetMessages.defaultExpectation.params != nil {
		mmGetMessages.mock.t.Fatalf("ServiceMock.GetMessages mock is already set by Expect")
	}

	if mmGetMessages.defaultExpectation.paramPtrs == nil {
		mmGetMessages.defaultExpectation.paramPtrs = &ServiceMockGetMessagesParamPtrs{}
	}
	mmGetMessages.defaultExpectation.paramPtrs.limit = &limit
	mmGetMessages.defaultExpectation.expectationOrigins.originLimit = minimock.CallerInfo(1)

	return mmGetMessages
}

// Inspect accepts an inspector function that has same arguments as the Service.GetMessages
func (mmGetMessages *mServiceMockGetMessages) Inspect(f func(chatID int, limit int)) *mServiceMockGetMessages {
	if mmGetMessages.mock.inspectFuncGetMessages != nil {
		mmGetMessages.mock.t.Fatalf("Inspect function is already set for ServiceMock.GetMessages")
	}

	mmGetMessages.mock.inspectFuncGetMessages = f

	return mmGetMessages
}

// Return sets up results that will be returned by Service.GetMessages
func (mmGetMessages *mServiceMockGetMessages) Return(cp1 *models.ChatWithMessages, err error) *ServiceMock {
	if mmGetMessages.mock.funcGetMessages != nil {
		mmGetMessages.mock.t.Fatalf("ServiceMock.GetMessages mock is already set by Set")
	}

	if mmGetMessages.defaultExpectation == nil {
		mmGetMessages.defaultExpectation = &ServiceMockGetMessagesExpectation{mock: mmGetMessages.mock}
	}
	mmGetMessages.defaultExpectation.results = &ServiceMockGetMessagesResults{cp1, err}
	mmGetMessages.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetMessages.mock
}

// Set uses given function f to mock the Service.GetMessages method
func (mmGetMessages *mServiceMockGetMessages) Set(f func(chatID int, limit int) (cp1 *models.ChatWithMessages, err error)) *ServiceMock {
	if mmGetMessages.defaultExpectation != nil {
		mmGetMessages.mock.t.Fatalf("Default expectation is already set for the Service.GetMessages method")
	}

	if len(mmGetMessages.expectations) > 0 {
		mmGetMessages.mock.t.Fatalf("Some expectations are already set for the Service.GetMessages method")
	}

	mmGetMessages.mock.funcGetMessages = f
	mmGetMessages.mock.funcGetMessagesOrigin = minimock.CallerInfo(1)
	return mmGetMessages.mock
}

// When sets expectation for the Service.GetMessages which will trigger the result defined by the following
// Then helper
func (mmGetMessages *mServiceMockGetMessages) When(chatID int, limit int) *ServiceMockGetMessagesExpectation {
	if mmGetMessages.mock.funcGetMessages != nil {
		mmGetMessages.mock.t.Fatalf("ServiceMock.GetMessages mock is already set by Set")
	}

	expectation := &ServiceMockGetMessagesExpectation{
		mock:               mmGetMessages.mock,
		params:             &ServiceMockGetMessagesParams{chatID, limit},
		expectationOrigins: ServiceMockGetMessagesExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetMessages.expectations = append(mmGetMessages.expectations, expectation)
	return expectation
}

// Then sets up Service.GetMessages return parameters for the expectation previously defined by the When method
func (e *ServiceMockGetMessagesExpectation) Then(cp1 *models.ChatWithMessages, err error) *ServiceMock {
	e.results = &ServiceMockGetMessagesResults{cp1, err}
	return e.mock
}

// Times sets number of times Service.GetMessages should be invoked
func (mmGetMessages *mServiceMockGetMessages) Times(n uint64) *mServiceMockGetMessages {
	if n == 0 {
		mmGetMessages.mock.t.Fatalf("Times of ServiceMock.GetMessages mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetMessages.expectedInvocations, n)
	mmGetMessages.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetMessages
}

func (mmGetMessages *mServiceMockGetMessages) invocationsDone() bool {
	if len(mmGetMessages.expectations) == 0 && mmGetMessages.defaultExpectation == nil && mmGetMessages.mock.funcGetMessages == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetMessages.mock.afterGetMessagesCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetMessages.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetMessages implements Service
func (mmGetMessages *ServiceMock) GetMessages(chatID int, limit int) (cp1 *models.ChatWithMessages, err error) {
	mm_atomic.AddUint64(&mmGetMessages.beforeGetMessagesCounter, 1)
	defer mm_atomic.AddUint64(&mmGetMessages.afterGetMessagesCounter, 1)

	mmGetMessages.t.Helper()

	if mmGetMessages.inspectFuncGetMessages != nil {
		mmGetMessages.inspectFuncGetMessages(chatID, limit)
	}

	mm_params := ServiceMockGetMessagesParams{chatID, limit}

	// Record call args
	mmGetMessages.GetMessagesMock.mutex.Lock()
	mmGetMessages.GetMessagesMock.callArgs = append(mmGetMessages.GetMessagesMock.callArgs, &mm_params)
	mmGetMessages.GetMessagesMock.mutex.Unlock()

	for _, e := range mmGetMessages.GetMessagesMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.cp1, e.results.err
		}
	}

	if mmGetMessages.GetMessagesMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetMessages.GetMessagesMock.defaultExpectation.Counter, 1)
		mm_want := mmGetMessages.GetMessagesMock.defaultExpectation.params
		mm_want_ptrs := mmGetMessages.GetMessagesMock.defaultExpectation.paramPtrs

		mm_got := ServiceMockGetMessagesParams{chatID, limit}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.chatID != nil && !minimock.Equal(*mm_want_ptrs.chatID, mm_got.chatID) {
				mmGetMessages.t.Errorf("ServiceMock.GetMessages got unexpected parameter chatID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetMessages.GetMessagesMock.defaultExpectation.expectationOrigins.originChatID, *mm_want_ptrs.chatID, mm_got.chatID, minimock.Diff(*mm_want_ptrs.chatID, mm_got.chatID))
			}

			if mm_want_ptrs.limit != nil && !minimock.Equal(*mm_want_ptrs.limit, mm_got.limit) {
				mmGetMessages.t.Errorf("ServiceMock.GetMessages got unexpected parameter limit, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetMessages.GetMessagesMock.defaultExpectation.expectationOrigins.originLimit, *mm_want_ptrs.limit, mm_got.limit, minimock.Diff(*mm_want_ptrs.limit, mm_got.limit))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetMessages.t.Errorf("ServiceMock.GetMessages got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetMessages.GetMessagesMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetMessages.GetMessagesMock.defaultExpectation.results
		if mm_results == nil {
			mmGetMessages.t.Fatal("No results are set for the ServiceMock.GetMessages")
		}
		return (*mm_results).cp1, (*mm_results).err
	}
	if mmGetMessages.funcGetMessages != nil {
		return mmGetMessages.funcGetMessages(chatID, limit)
	}
	mmGetMessages.t.Fatalf("Unexpected call to ServiceMock.GetMessages. %v %v", chatID, limit)
	return
}

// GetMessagesAfterCounter returns a count of finished ServiceMock.GetMessages invocations
func (mmGetMessages *ServiceMock) GetMessagesAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetMessages.afterGetMessagesCounter)
}

// GetMessagesBeforeCounter returns a count of ServiceMock.GetMessages invocations
func (mmGetMessages *ServiceMock) GetMessagesBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetMessages.beforeGetMessagesCounter)
}

// Calls returns a list of arguments used in each call to ServiceMock.GetMessages.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetMessages *mServiceMockGetMessages) Calls() []*ServiceMockGetMessagesParams {
	mmGetMessages.mutex.RLock()

	argCopy := make([]*ServiceMockGetMessagesParams, len(mmGetMessages.callArgs))
	copy(argCopy, mmGetMessages.callArgs)

	mmGetMessages.mutex.RUnlock()

	return argCopy
}

// MinimockGetMessagesDone returns true if the count of the GetMessages invocations corresponds
// the number of defined expectations
func (m *ServiceMock) MinimockGetMessagesDone() bool {
	if m.GetMessagesMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetMessagesMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetMessagesMock.invocationsDone()
}

// MinimockGetMessagesInspect logs each unmet expectation
func (m *ServiceMock) MinimockGetMessagesInspect() {
	for _, e := range m.GetMessagesMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ServiceMock.GetMessages at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetMessagesCounter := mm_atomic.LoadUint64(&m.afterGetMessagesCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetMessagesMock.defaultExpectation != nil && afterGetMessagesCounter < 1 {
		if m.GetMessagesMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ServiceMock.GetMessages at\n%s", m.GetMessagesMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ServiceMock.GetMessages at\n%s with params: %#v", m.GetMessagesMock.defaultExpectation.expectationOrigins.origin, *m.GetMessagesMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetMessages != nil && afterGetMessagesCounter < 1 {
		m.t.Errorf("Expected call to ServiceMock.GetMessages at\n%s", m.funcGetMessagesOrigin)
	}

	if !m.GetMessagesMock.invocationsDone() && afterGetMessagesCounter > 0 {
		m.t.Errorf("Expected %d calls to ServiceMock.GetMessages at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetMessagesMock.expectedInvocations), m.GetMessagesMock.expectedInvocationsOrigin, afterGetMessagesCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateChatInspect()

			m.MinimockCreateMessageInspect()

			m.MinimockDeleteChatInspect()

			m.MinimockGetMessagesInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateChatDone() &&
		m.MinimockCreateMessageDone() &&
		m.MinimockDeleteChatDone() &&
		m.MinimockGetMessagesDone()
}
